<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_14%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E7%B4%A2%E5%BC%95%E3%80%81%E5%88%87%E7%89%87%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
print("--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------")

# 實際操作: 多維陣列的索引、切片操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 多維陣列的索引 Indexing
print("\n--------(索引: Indexing)--------")

# 單維度的資料
data = np.array([1, 5, 2, 10])
print(f"\n【原始資料 data】: {data}")
print(f"【取得 data[0] 的資料】: {data[0]}")
print(f"【取得 data[2] 的資料】: {data[2]}")

# 多維度的資料
data = np.array([
    [0, 1],[10, -5],[2, 6]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0,1] 的資料】: {data[0,1]}")   #1
print(f"【取得 data[1,0] 的資料】: {data[1,0]}")   #10
print(f"【取得 data[2,0] 的資料】: {data[2,0]}")   #2

#-------------------------------------------------------------

# 多維陣列的切片 Slicing
print("\n--------(切片: Slicing)--------")

# 單維度的切片
data = np.array([-1, -5, 2, 3])
print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0:3] 的資料】: {data[0:3]}")   #[-1, -5, 2]
print(f"【取得 data[:2] 的資料】: {data[:2]}")    #[-1, -5]
print(f"【取得 data[2:] 的資料】: {data[2:]}")    #[2, 3]
print(f"【取得 data[:] 的資料】: {data[:]}")     #[-1, -5, 2, 3]

# 多維度的切片
data = np.array([
    [0, 1, 2],[3, 4, 5],
    [5, 4, 3],[2, 1, 0]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[1:3, 0:2] 的資料】\n{data[1:3, 0:2]}")   #[[3, 4],[5, 4]]
print(f"【取得 data[0:2, 1] 的資料】\n{data[0:2, 1]}")     #[1, 4]


# §補充資料:
# 使用單一數字（整數）來取值時，NumPy 會進行「降維」；而使用範圍切片（:）時，則會「保留原有的維度」
# 範例: print(f"【取得 data[0:2, 1:2] 的資料】\n{data[0:2, 1:2]}")
# 輸出: [[1],[4]]


# 使用 ... 代表「我全都要」
data = np.array([
    [
        [8, 1, 3],
        [-5, 5, 2]
    ],
    [
        [0, 1, 6],
        [4, 4, -3]
    ]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0, ...] 的資料】\n{data[0, ...]}")
# 輸出: [[8, 1, 3],[-5, 5, 2]]

print(f"【取得 data[..., 1:3] 的資料】\n{data[..., 1:3]}")
# 輸出: [[[1, 3],[5, 2]],[[1, 6],[4, -3]]]














#======================
# 索引 (Indexing)
#======================

# 資料的索引
# 概念上和 Python 列表的索引相同
# 按照順序，每個資料都有一個索引 (編碼)，從 0 開始遞增
# 透過 多維陣列[索引] 的語法可以取得對應的資料

data = np.array([3, 4, 1])

data[0]  #3
data[1]  #4
data[2]  #1

#-------------------------------------------------------------

# 多維度資料的索引
# 使用逗號分開不同維度的索引
# 透過 多維陣列[索引,索引,...] 的語法可以取得對應的資料

data = np.array([
    [1, 5, 2],
    [3, -1, 10]
])

data[0,2]  #2
data[1,1]  #-1
data[1,0]  #3


#=====================
# 切片 (Slicing)
#=====================

# 資料的切片
# 取得多維陣列中的部分資料
# 以下語法取得對應的資料 多維陣列[開始索引 : 結束索引]

data = np.array([3, 4, 1, 5])
data[0:2]  #[3, 4]
data[1:4]  #[4, 1, 5]
data[2:]  #[1, 5]
data[:3]  #[3, 4, 1]
data[:]  #[3, 4, 1, 5]

#-------------------------------------------------------------

# 多維度資料的切片
# 分別決定每一個維度的索引範圍
# 以下語法取得對應的資料
# 多維陣列[
#    開始索引:結束索引,
#    開始索引:結束索引
#    ...
#    ]

data = np.array([
    [3, 1, 2],[1, 2, 5],
    [5, 2, 2],[3, -5, 1]
])

data[2:4, 1:3]  #[[2, 2],[-5, 1]]
data[0:2, 1]   #[1, 2]

#-------------------------------------------------------------

# 多維度資料的切片
# 使用 ... 代表「我全都要」
# 參考以下範例

data = np.array([
    [
        [3, 1, 2],[1, 0, 5]
    ],
    [
        [5, 4, 3],[1, 3, -3]
    ]
])

data[1,...]  #[[5, 4, 3],[1, 3, -3]]
data[...,0:2] #[[[3, 1],[1, 0]],[[5, 4],[1, 3]]]


--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------

--------(索引: Indexing)--------

【原始資料 data】: [ 1  5  2 10]
【取得 data[0] 的資料】: 1
【取得 data[2] 的資料】: 2

【原始資料 data】
[[ 0  1]
 [10 -5]
 [ 2  6]]
【取得 data[0,1] 的資料】: 1
【取得 data[1,0] 的資料】: 10
【取得 data[2,0] 的資料】: 2

--------(切片: Slicing)--------

【原始資料 data】
[-1 -5  2  3]
【取得 data[0:3] 的資料】: [-1 -5  2]
【取得 data[:2] 的資料】: [-1 -5]
【取得 data[2:] 的資料】: [2 3]
【取得 data[:] 的資料】: [-1 -5  2  3]

【原始資料 data】
[[0 1 2]
 [3 4 5]
 [5 4 3]
 [2 1 0]]
【取得 data[1:3, 0:2] 的資料】
[[3 4]
 [5 4]]
【取得 data[0:2, 1] 的資料】
[1 4]

【原始資料 data】
[[[ 8  1  3]
  [-5  5  2]]

 [[ 0  1  6]
  [ 4  4 -3]]]
【取得 data[0, ...] 的資料】
[[ 8  1  3]
 [-5  5  2]]
【取得 data[..., 1:3] 的資料】
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]


array([[[3, 1],
        [1, 0]],

       [[5, 4],
        [1, 3]]])

In [ ]:
|