<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_11%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
print("--------(NumPy: 多維陣列 ndarray 基礎)--------")

# 實際操作: 多維陣列的各種建立方式

# 載入 NumPy 套件
import numpy as np

#-------------------------------------------------------------

# 建立一維陣列

data= np.array([3, 2, 6, 4])
print(f"\n【一維陣列】: {data}")

# 創造一個有四個資料的一維陣列，資料未指定
data= np.empty(4)
print(f"【資料未指定的一維陣列】: {data}")

# 創造一個有 3 個資料且都是 0 的一維陣列
data= np.zeros(3)
print(f"【三個資料都是 0 的一維陣列】: {data}")

# 創造一個有 3 個資料且都是 1 的一維陣列
data= np.ones(3)
print(f"【三個資料都是 1 的一維陣列】: {data}")

# 創造 5 個連續的資料的一維陣列
data= np.arange(5)
print(f"【五個連續資料的一維陣列】: {data}\n")

#-------------------------------------------------------------

# 建立二維陣列

data= np.array([
    [2, 3, 2],
    [1, 5, 2],
    [4, 2, 1]
])
print(f"【3x3 的二維陣列】\n{data}\n")

# 創造一個 3x3 的二維陣列，資料未指定
data= np.empty([3, 3])
print(f"【3x3 資料未指定的二維陣列】\n{data}\n")

# 創造一個 2x3 且資料都是 1 的二維陣列
data= np.ones([2, 3])
print(f"【2x3 資料都是 1 的二維陣列】\n{data}\n")

#-------------------------------------------------------------

# 建立三維陣列

data= np.array([
    [
        [3, 1],[1, 2]
    ],
     [
         [2, 5],[10, 2]
     ]
])
print(f"【2x2x2 的三維資料】\n{data}\n")

# 創造一個 3x1x3 且資料都是 0 的三維陣列
data= np.zeros([3, 1, 3])
print(f"【3x1x3 資料都是 0 的三維陣列】\n{data}\n")

#-------------------------------------------------------------

# 建立高維陣列

data= np.array([
    [
        [
            [3, 2, 1],
            [5, 5, 10]
        ]
    ]
])
print(f"【1x1x2x3 的四維陣列】\n{data}\n")

# 創造一個 2x1x1x2 且資料都是 1 的四維陣列
data= np.ones([2, 1, 1, 2])
print(f"【2x1x1x2 且資料都是 1 的四維陣列】\n{data}\n")

















#-----------------------------------------------
# 多維陣列: N-Dimensional Array (ndarray)
#-----------------------------------------------

# 多維陣列介紹:
# 多維陣列 ndarray 是 Numpy 的核心物件
# 運算速度遠高於列表
# 適合多維度的數值運算

#------------------
# 建立多維陣列
#------------------

# 建立一維陣列: 最基本的陣列形式

# 根據列表建立
np.array([3, 5, 4])
# 建立資料未指定的一維陣列
np.empty(3)
# 建立資料都是 0 的一維陣列
np.zeros(3)
# 建立資料都是 1 的一維陣列
np.ones(3)
# 建立連續資料的一維陣列
np.arange(3)

#-------------------------------------------------------------

# 建立二維陣列: 類似表格的概念

# 根據列表建立
np.array([
    [1, 2],
    [3, 2],
    [5, 0]
])

# 建立資料未指定的二維陣列
np.empty([3, 2])
# 建立資料都是 0 的二維陣列
np.zeros([3, 2])
# 建立資料都是 1 的二維陣列
np.ones([3, 2])

#-------------------------------------------------------------

# 建立三維陣列: 類似空間座標系統的概念

# 根據列表建立
np.array([
    [#第一頁
    [1, 2, 3],   #第一列
    [4, 5, 6]   #第二列
  ],
    [#第二頁
    [7, 8, 9],
    [10, 11, 12]
  ]
])

# 建立資料未指定的三維陣列
np.empty([2, 2, 3])

# 建立資料都是 0 的三維陣列
np.zeros([2, 2, 3])

#-------------------------------------------------------------

# 建立高維陣列: 超過三個維度的陣列

# 超過三個維度的概念，需要完全以邏輯來推演

# 以下是 1x1x2x2 的四維陣列
np.array([
    [
        [
            [3, 2],
            [5, 4]
        ]
    ]
])


#-------------------------------------------------------------
# §補充資料: np.empty() 不是「真的空」
# 在實務上要特別小心：np.empty() 所建立的陣列，裡面的數字並不是空的，也不是 0，
# 而是記憶體中隨機殘留的垃圾數值 (Garbage Values)
# 意義只是為了用最快的速度要到一塊記憶體空間，所以在使用它之前，
# 「必須保證後續的程式碼會把所有資料填滿」，否則會算出一堆亂碼
# 如果不確定，可以優先使用安全的 np.zeros()
#-------------------------------------------------------------


--------(NumPy: 多維陣列 ndarray 基礎)--------

【一維陣列】: [3 2 6 4]
【資料未指定的一維陣列】: [1. 1. 1. 1.]
【三個資料都是 0 的一維陣列】: [0. 0. 0.]
【三個資料都是 1 的一維陣列】: [1. 1. 1.]
【五個連續資料的一維陣列】: [0 1 2 3 4]

【3x3 的二維陣列】
[[2 3 2]
 [1 5 2]
 [4 2 1]]

【3x3 資料未指定的二維陣列】
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

【2x3 資料都是 1 的二維陣列】
[[1. 1. 1.]
 [1. 1. 1.]]

【2x2x2 的三維資料】
[[[ 3  1]
  [ 1  2]]

 [[ 2  5]
  [10  2]]]

【3x1x3 資料都是 0 的三維陣列】
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]

【1x1x2x3 的四維陣列】
[[[[ 3  2  1]
   [ 5  5 10]]]]

【2x1x1x2 且資料都是 1 的四維陣列】
[[[[1. 1.]]]


 [[[1. 1.]]]]



array([[[[3, 2],
         [5, 4]]]])