<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_15_02%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E5%88%87%E5%89%B2%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("--------(NumPy: 多維陣列 ndarray 切割操作)--------")

# 實際操作: 多維陣列的切割操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 準備測試資料
arr = np.array([          #2x6
    [2, 4, 6, 8, 10, 12],
    [1, 3, 5, 7, 9, 11]
])

# 根據第一個維度切割
result1 = np.vsplit(arr, 2)
print(f"\n【arr 陣列】\n{arr}\n")
print(f"【切割 第一個維度 後的陣列】\n{result1}")
"""
  1x6
    [[2, 4, 6, 8 ,10, 12]]
  1x6
    [[1, 3, 5, 7, 9, 11]]
"""

# 根據第二個維度切割
result2 = np.hsplit(arr, 2)
print(f"【切割 第二個維度 後的陣列】\n{result2}")
"""
  2x3
    [[2, 4, 6],[1, 3, 5]]
  2x3
    [[8, 10, 12],[7, 9, 11]]
"""

# 根據第二個維度切割成 3 個陣列
result3 = np.hsplit(arr, 3)
print(f"【切割 第二個維度 (三個陣列) 後的陣列】\n{result3}")
"""
  2x2
    [[2, 4],[1, 3]]
  2x2
    [[6, 8],[5, 7]]
  2x2
    [[10, 12],[9, 11]]
"""



#=======================
# 切割 (Splitting)
#=======================

# 切割操作
# 將一個多維陣列，切割成多個

# 根據第一個維度切割
# np.vsplit(陣列, 切割數量)

# 根據第二個維度切割
# np.hsplit(陣列, 切割數量)

#-------------------------------------------------------------

# 切割範例
arr1 = np.array([    #2x4
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

result1 = np.vsplit(arr1, 2)
#[[1, 2, 3, 4]]  #1x4
#[[5, 6, 7, 8]]  #1x4

result2 = np.hsplit(arr1, 2)
#[[1, 2],[5, 6]]  #2x2
#[[3, 4],[7, 8]]  #2x2


--------(NumPy: 多維陣列 ndarray 切割操作)--------

【arr 陣列】
[[ 2  4  6  8 10 12]
 [ 1  3  5  7  9 11]]

【切割 第一個維度 後的陣列】
[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  7,  9, 11]])]
【切割 第二個維度 後的陣列】
[array([[2, 4, 6],
       [1, 3, 5]]), array([[ 8, 10, 12],
       [ 7,  9, 11]])]
【切割 第二個維度 (三個陣列) 後的陣列】
[array([[2, 4],
       [1, 3]]), array([[6, 8],
       [5, 7]]), array([[10, 12],
       [ 9, 11]])]


In [99]:
import numpy as np
print("--------(NumPy: 多維陣列 ndarray 切割操作)--------")

#===============================================================
# 1. 垂直切割 (Vertical Split): np.vsplit()
# 橫向切一刀，把陣列「上下」分開，常用於「將大批次數據分段」
#===============================================================
print("\n--------(垂直切割: np.vsplit)--------")

# §實驗情境: 訊號分段處理
# 假設連續量測了 4 個時間點的 [電壓，電流] 數據 (4x2 陣列)
sensor_data = np.array([  #4x2
    [5.0, 0.2],
    [10.0, 0.4],
    [15.0, 0.6],
    [20.0, 0.8]
])

# 需求: 將這 4 筆數據，平均切割成 2 個批次 (Batch)
# 語法邏輯: np.vsplit(陣列, 切割份數)
# 回傳的結果是一個 Python 「串列 (List)」，裡面裝著切好的小陣列
split_result = np.vsplit(sensor_data, 2)
print(f"\n【原始數據 sensor_data (4x2)】\n{sensor_data}")  #4x2
print(f"\n【垂直分割後的數據】\n{split_result}")
print(f"【垂直分割後的 第一批數據】\n{split_result[0]}")   #2x2
print(f"【垂直分割後的 第二批數據】\n{split_result[1]}")   #2x2

# 實務技巧: 直接使用 Python 的「解包 (Unpacking)」語法，用一行程式碼接收所有回傳值
batch1, batch2 = np.vsplit(sensor_data, 2)
print(f"【使用解包語法取得 batch1】\n{batch1}\n")


#=================================================================
# 2. 水平切割 (Horizontal Split): np.hsplit()
# 直直切一刀，把陣列「左右」分開，常用於「把資料表的欄位拆開」
#=================================================================
print("--------(水平切割: np.hsplit)--------")

# §實驗情境: 雙通道示波器數據拆解
# 假設從示波器匯出了一個 3x3 的資料表，三個欄位分別是: [時間， CH1電壓， CH2電壓]
osc_data = np.array([
    [0.1, 1.5, -1.0],
    [0.2, 3.2, -2.1],
    [0.3, 4.8, -3.5]
])

print(f"\n【原始示波器數據表 (3x3)】\n{osc_data}\n")

# 需求: 把這 3 個欄位完全拆開，變成 3 個獨立的行向量 (Column Vector)
# 語法邏輯: np.hsplit(陣列, 切割份數)
time_col, ch1_col, ch2_col = np.hsplit(osc_data, 3)

print(f"\n【拆解出的 時間 行向量】\n{time_col}")
print(f"【拆解出的 CH1 電壓 行向量】\n{ch1_col}")
print(f"【拆解出的 CH2 電壓 行向量】\n{ch2_col}\n")
#拆解出來的形狀都是 3x1 的二維陣列

#-------------------------------------------------------------

# §實務補充: 準備繪圖數據 (Matplotlib)

# 雖然將資料拆解出來，但它們現在是 3x1 的「二維行向量」，如果要丟入 Matplotlib 畫圖，通常需要轉回單純的「一維陣列 (3,)」
# 這時就可以結合近期學過的 np.squeeze() (消除長度為 1 的維度)
time_1d = np.squeeze(time_col)
ch1_1d = np.squeeze(ch1_col)
ch2_1d = np.squeeze(ch2_col)

print(f"【轉換為一維陣列供畫圖使用 time_1d】: {time_1d}")
print(f"【time_1d 形狀檢查】: {time_1d.shape}")


#=========================================================
# 3. 萬用切割函式: np.split() 與 「非等分切割」
# 除了指定等分數量，還可以指定「切在哪個位置 (索引)」
#=========================================================
print("\n--------(萬用切割: np.split 與非等分切割)--------")

# 準備一條長度為 6 的一維訊號陣列
signal = np.array([10, 20, 30, 40, 50, 60])


# 方法 A: 等分切割 (切成 3 等分)
# axis=0， 針對第一個維度切割
equal_splits = np.split(signal, 3, axis=0)
print(f"\n【等分切割 (切 3 份)】\n{equal_splits}\n")


# 方法 B: 非等分切割 (指定切點索引)
# §實驗情境: 想把前 2 個數據當作「訓練集」，剩下的當作「測試集」
# 語法邏輯: 傳入一個包含切點索引的 List，例如 [2] 代表「在索引 2 的地方切一刀」
train_data, test_data = np.split(signal, [2])

print(f"在索引 [2] 切一刀: ")
print(f"【訓練集 (前半段)】: {train_data}")   #拿到索引 0, 1
print(f"【測試集 (後半段)】: {test_data}\n")   #拿到索引 2, 3, 4, 5

train_data, test_data1, test_data2 = np.split(signal, [2, 5])
print(f"在索引 [2, 5] 各切一刀: ")
print(f"【索引 [2] 之前的數據】: {train_data}")        #拿到索引 0, 1
print(f"【索引 [2] 到 [5] 之間的數據】: {test_data1}")    #拿到索引 2, 3, 4
print(f"【索引 [5] 之後的數據】: {test_data2}")        #拿到索引 5


--------(NumPy: 多維陣列 ndarray 切割操作)--------

--------(垂直切割: np.vsplit)--------

【原始數據 sensor_data (4x2)】
[[ 5.   0.2]
 [10.   0.4]
 [15.   0.6]
 [20.   0.8]]

【垂直分割後的數據】
[array([[ 5. ,  0.2],
       [10. ,  0.4]]), array([[15. ,  0.6],
       [20. ,  0.8]])]
【垂直分割後的 第一批數據】
[[ 5.   0.2]
 [10.   0.4]]
【垂直分割後的 第二批數據】
[[15.   0.6]
 [20.   0.8]]
【使用解包語法取得 batch1】
[[ 5.   0.2]
 [10.   0.4]]

--------(水平切割: np.hsplit)--------

【原始示波器數據表 (3x3)】
[[ 0.1  1.5 -1. ]
 [ 0.2  3.2 -2.1]
 [ 0.3  4.8 -3.5]]


【拆解出的 時間 行向量】
[[0.1]
 [0.2]
 [0.3]]
【拆解出的 CH1 電壓 行向量】
[[1.5]
 [3.2]
 [4.8]]
【拆解出的 CH2 電壓 行向量】
[[-1. ]
 [-2.1]
 [-3.5]]

【轉換為一維陣列供畫圖使用 time_1d】: [0.1 0.2 0.3]
【time_1d 形狀檢查】: (3,)

--------(萬用切割: np.split 與非等分切割)--------

【等分切割 (切 3 份)】
[array([10, 20]), array([30, 40]), array([50, 60])]

在索引 [2] 切一刀: 
【訓練集 (前半段)】: [10 20]
【測試集 (後半段)】: [30 40 50 60]

在索引 [2, 5] 各切一刀: 
【索引 [2] 之前的數據】: [10 20]
【索引 [2] 到 [5] 之間的數據】: [30 40 50]
【索引 [5] 之後的數據】: [60]
