<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_13%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E7%B6%AD%E5%BA%A6%E3%80%81%E5%BD%A2%E7%8B%80%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
print("--------(NumPy: 多維陣列 ndarray 維度、形狀操作)--------")

# 實際操作: 多維陣列的維度、形狀操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# .shape: 觀察資料形狀
print("\n--------(.shape: 觀察資料形狀)--------")

data = np.ones(10)   #[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
print(f"\n【資料形狀】: {data.shape}")

data = np.array([
    [3, 1, 5],
    [1, 2, 3]
])
print(f"【資料形狀】: {data.shape}\n")

#-------------------------------------------------------------

# .T: 資料轉置
print("--------(.T: 資料轉置)--------")

data = np.array([
    [2, 4, 1],
    [1, 5, 0]
])
print(f"\n【資料形狀】: {data.shape}")     #(2,3)
print(f"【資料轉置】\n{data.T}")
print(f"【資料轉置形狀】: {data.T.shape}\n")   #(3,2)

#-------------------------------------------------------------

# .ravel(): 扁平化資料
print("--------(.ravel(): 扁平化資料)--------")

data= np.array([
    [[2, 1, 3],[1, 2, 3]],
    [[0, 2, 1],[8, 9, 10]]
])                     #(2,2,3)
newData = data.ravel()
print(f"\n【資料原始的形狀】\n{data}")
print(f"【將資料拆開扁平化】: {newData}")
print(f"【扁平化後資料的形狀】: {newData.shape}\n")

#-------------------------------------------------------------

# .reshape(): 重塑資料形狀
print("--------(.reshape(): 重塑資料形狀)--------")

data = np.array([
    [[2, 1, 3],[1, 2, 3]],
    [[0, 2, 1],[8, 9, 10]]
])                     #(2,2,3)=12
newData = data.reshape(3,4)        #(3,4)=12
# newData = data.reshape(1,2,6)     #(1,2,6)=12
# newData = data.reshape(3,5)      #(3,5)=15 (錯誤)
print(f"\n【原始的資料】\n{data}")
print(f"【重塑後的資料】\n{newData}\n")

data = np.zeros(18).reshape(3,6)
print(f"【將 18 個都是 0 的資料重塑為 (3x6) 陣列】\n{data}")
data = np.arange(9).reshape(3,3)
print(f"【將 9 個連續的資料重塑為 (3x3) 陣列】\n{data}")
print(f"【轉置 (3x3) 的陣列】\n{data.T}")

#-------------------------------------------------------------

# 補充資料: 一維陣列的轉置方法
print("--------(補充: 一維陣列的轉置與 -1 自動推算)--------")

# 直接對一個「一維陣列」使用 .T，什麼事都不會發生
# 因為形狀為 (N,) 的一維陣列，在 NumPy 的底層邏輯裡不是列、也不是行，就只是一條單純的數據
data_1d = np.array([1, 2, 3])
print(f"\n【一維陣列原始形狀】: {data_1d.shape}")
print(f"【一維陣列 .T 轉置後形狀】: {data_1d.T.shape}")    #.T 轉置後一維陣列形狀沒有改變


# 【解法】: 利用 .reshape() 強制定義為二維的 「行向量」 或 「列向量」
# §補充技巧: 使用 「-1」 交給程式自動推算
# 在 .reshape() 中填入 -1 ，代表「我不確定這個維度是多少，請依照資料總數自動推算」
# 實務優點: 處理實驗擷取的數據時，不管資料是 10 筆或是 1000 筆，程式都能自動適應，不會報錯

# 1. 轉換成行向量 (Column Vector)
# 邏輯意義: 「我要強制變成 1 欄，總共有幾列請電腦自己計算 (3÷1=3)」
col_vector = data_1d.reshape(-1, 1)
print(f"\n【轉換為行向量後的形狀】: {col_vector.shape}")
print(f"【轉換為行向量後的資料】\n{col_vector}")

# 2. 轉換成列向量 (Row Vector)
# 邏輯意義: 「我要強制變成 1 列，總共有幾欄請電腦自己計算 (3÷1=3)」
row_vector = data_1d.reshape(1, -1)
print(f"【轉換為列向量後的形狀】: {row_vector.shape}")
print(f"【轉換為列向量後的資料】\n{row_vector}\n")











#-----------------------------------------------------
# 多維陣列的形狀 Shape
# 維度: 資料的層次
# 形狀: 同時表達資料的層次，和每個層次的資料數量
#-----------------------------------------------------

# 原始資料是 8 個數字，可以被表達成不同的形狀

# [1, 2, 3, 4, 5, 6, 7, 8]  #形狀:(8,)

# [                 #形狀:(2,4)
# [1, 2, 3, 4],
# [5, 6, 7, 8]
# ]

# [                 #形狀:(2,2,2)
# [[1, 2],[3, 4]],
# [[5, 6],[7, 8]]
# ]


#-----------------------------------------
# 維度、形狀的相關操作
#-----------------------------------------

# 觀察資料形狀: 利用 shape 屬性取得多維陣列的形狀

# 程式範例:
# data = np.array([3, 4, 1])
# data.shape    #形狀:(3,)

# data = np.array([
# [2, 4],
# [1, 5]
# ])
# data.shape    #形狀:(2,2)

#-------------------------------------------------------------

# 資料轉置: 利用 T 屬性取得多維陣列的轉置

# 程式範例:
# data = np.array([
# [2, 4, 1],
# [1, 5, 0]
# ])
# data.shape    #形狀:(2x3)
# data.T.shape   #形狀:(3x2)

#-------------------------------------------------------------

# 扁平化資料: 把多維度的資料打平成一維陣列

# 程式範例:
# data = np.array([
# [1, 2],[3, 4],
# [5, 6],[7, 8]
# ])
# data.ravel()   #形狀:[1, 2, 3, 4, 5, 6, 7, 8]

#-------------------------------------------------------------

# 重塑資料形狀: 改變資料的形狀，資料數量必須要一樣

# 程式範例:
# data = np.array([
# [[1, 2],[3, 4]],
# [[5, 6],[7, 8]]
# ])           #形狀:(2x2x2)= 8
# data = data.reshape(4,2)  #形狀:(4x2)= 8
# data = data.reshape(3,3)  #形狀:(3x3)= 9 (錯誤)

# data = np.zeros(18).reshape(2, 3, 3)  #形狀:(2x3x3)= 18


--------(NumPy: 多維陣列 ndarray 維度、形狀操作)--------

--------(.shape: 觀察資料形狀)--------

【資料形狀】: (10,)
【資料形狀】: (2, 3)

--------(.T: 資料轉置)--------

【資料形狀】: (2, 3)
【資料轉置】
[[2 1]
 [4 5]
 [1 0]]
【資料轉置形狀】: (3, 2)

--------(.ravel(): 扁平化資料)--------

【資料原始的形狀】
[[[ 2  1  3]
  [ 1  2  3]]

 [[ 0  2  1]
  [ 8  9 10]]]
【將資料拆開扁平化】: [ 2  1  3  1  2  3  0  2  1  8  9 10]
【扁平化後資料的形狀】: (12,)

--------(.reshape(): 重塑資料形狀)--------

【原始的資料】
[[[ 2  1  3]
  [ 1  2  3]]

 [[ 0  2  1]
  [ 8  9 10]]]
【重塑後的資料】
[[ 2  1  3  1]
 [ 2  3  0  2]
 [ 1  8  9 10]]

【將 18 個都是 0 的資料重塑為 (3x6) 陣列】
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
【將 9 個連續的資料重塑為 (3x3) 陣列】
[[0 1 2]
 [3 4 5]
 [6 7 8]]
【轉置 (3x3) 的陣列】
[[0 3 6]
 [1 4 7]
 [2 5 8]]
--------(補充: 一維陣列的轉置與 -1 自動推算)--------

【一維陣列原始形狀】: (3,)
【一維陣列 .T 轉置後形狀】: (3,)

【轉換為行向量後的形狀】: (3, 1)
【轉換為行向量後的資料】
[[1]
 [2]
 [3]]
【轉換為列向量後的形狀】: (1, 3)
【轉換為列向量後的資料】
[[1 2 3]]

