<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_12%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E5%9F%BA%E7%A4%8E%E9%81%8B%E7%AE%97%E5%8A%9F%E8%83%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
print("--------(NumPy: 多維陣列 ndarray 基礎運算功能)--------")

# 實際操作: 多維陣列的各種運算功能

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 逐元運算 (Elementwise)
print("\n--------(Elementwise: 逐元運算)--------")

# 建立兩個形狀相同 (長度為 3) 的一維陣列
data1= np.array([3, 2, 10])
data2= np.array([1, 3, 6])

# 形狀相同，可以順利逐元相加
result= data1 + data2
print(f"\ndata1: {data1}")
print(f"data2: {data2}\n")
print(f"【相加結果】: {result}")
#[3+1, 2+3, 10+6]

# 逐元相乘
result= data1 * data2
print(f"【乘法結果】: {result}")
#[3*1, 2*3, 10*6]

# 逐元比較: 大於 (>)
result= data1 > data2
print(f"【data1 > data2】: {result}")
#[3>1 (True), 2>3 (False), 10>6 (True)]

# 逐元比較: 等於 (==)
result= data1 == data2
print(f"【是否相等】: {result}\n")
#[3==1 (False), 2==3 (False), 10==6 (False)]

#-------------------------------------------------------------

# 矩陣運算 (Matrix)
print("--------(Matrix: 矩陣運算)--------")

# 建立兩個多維陣列
data1= np.array([    #1x2
    [1, 3]
])

data2= np.array([    #2x3
    [2, -1, 3],
    [-2, 4, 1]
])

# 1. 矩陣內積/矩陣乘法 (Dot Product/Matrix Multiplication)
# §數學條件: 第一個矩陣的行必須等於第二個矩陣的列
# 運算過程: (1x2)·(2x3) → (1x3)
result= data1.dot(data2)
# §補充技巧: Python 3.5 後，更推薦使用 data1@data2 這個矩陣乘法符號
print(f"\ndata1: {data1}")
print(f"data2: \n{data2}")
print(f"\n【內積結果】\n{result}\n")

# 2. 張量外積 (Outer Product)
# §數學定義: 兩陣列元素互相交乘，將長度 2 與長度 6 的陣列，展開成 2x6 的大矩陣
result= np.outer(data1, data2)
print(f"【張量外積結果】\n{result}\n")

# 3. 向量外積/叉積 (Cross Product) - 電磁學與物理工程常用
# §數學定義: 計算兩個 3D 向量的法向量
vec1= np.array([1, 0, 0])   #X軸向量
vec2= np.array([0, 1, 0])   #Y軸向量
result_cross= np.cross(vec1, vec2)
print(f"【向量外積 (叉積) 結果】: {result_cross}\n")  #結果為: [0, 0, 1] (Z軸向量)

#-------------------------------------------------------------

# 統計運算 (Statistics)
print("--------(Statistics: 統計運算)--------")

# 建立一個多維陣列
data= np.array([
    [2, 1, 7],  #2x3
    [-5 ,3, 8]
])

# 1. 全域運算 (對整個陣列的所有元素進行統計)

# .sum(): 取得陣列加總
result= data.sum()
print(f"\ndata:\n{data}")
print(f"\n【總和】: {result}")

# .max(): 取得陣列最大值
result= data.max()
print(f"【最大值】: {result}")

# .mean(): 取得陣列平均值
result= data.mean()
print(f"【平均值】: {result:.2f}")

# .std(): 取得陣列母體標準差
result= data.std()
print(f"【母體標準差】: {result:.2f}")

# §補充資料: NumPy 的 .std() 預設為「母體標準差」
# 如果要計算實驗常用的「樣本標準差 (分母為 N-1)」，需要加上 ddof=1 參數
result= data.std(ddof=1)
print(f"【樣本標準差 (ddof=1)】{result:.2f}")


# 2. 指定軸向運算 (使用 axis 參數)

# 針對第一個維度做總和
# axis=0: 針對第一個維度運算 (往下壓縮，最後得到一排每一欄的結果)
result= data.sum(axis=0)  #針對欄做總和 Column (針對第一個維度做總和)
print(f"\n【針對第一個維度 (axis=0) 做總和】: {result}")

# 針對第二個維度做總和
# axis=1: 針對第二個維度運算 (往右壓縮，最後得到一排每一列的結果)
result= data.sum(axis=1)  #針對列做總和 Row (針對第二個維度做總和)
print(f"【針對第二個維度 (axis=1) 做總和】: {result}")

# 針對第一個維度取得最大值
result= data.max(axis=0)
print(f"【針對第一個維度 (axis=0) 找最大值】: {result}")

# 針對第二個維度取得平均值
result= data.mean(axis=1)
print(f"【針對第二個維度 (axis=1) 找平均值】: {result}")


# 3. 累加運算 (Cumulative Sum)
# 實務意義: 常用於計算連續訊號的數值積分、累積能量或累積機率

# 未指定 axis: 陣列會先被攤平成一維，然後逐一往後累加
result= data.cumsum()
print(f"\n【逐值累加】\n{result}")

# axis=0: 針對第一個維度 (垂直往下) 做逐值累加
result= data.cumsum(axis=0)  #針對欄做逐值累加 Column (針對第一個維度做逐值累加)
print(f"【針對第一個維度做逐值累加】\n{result}\n")












#--------------------------------------------------------
# 多維陣列的運算: 基於 ndarray 多維陣列的運算功能
#--------------------------------------------------------

# 逐元運算 (elementwise)
# 矩陣運算 (matrix)
# 統計運算 (statistics)

#-------------------------------------------------------------

# 逐元運算: 針對陣列中的每個資料，逐一進行基本運算

# 建立兩個多維陣列
data1= np.array([3, 4, 1])
data2= np.array([-2, 5, -8])

# 逐一元素運算
data1 + data2
data1 - data2
data1 * data2
data1 / data2
data1 > data2
data1 == data2
data1 <= data2

#-------------------------------------------------------------

# 矩陣運算: 針對兩個陣列進行矩陣運算

# 建立兩個多維陣列
data1= np.array([    #1x2
    [2,1]
])

data2= np.array([    #2x3
    [3, 2, 0],
    [3, 1, -1]
])

# 矩陣運算
data1.dot(data2)      #內積 1x3
data1@data2        #內積 1x3
np.outer(data1, data2)  #外積 2x6

#-------------------------------------------------------------

# 統計運算: 針對單一陣列進行統計運算

# 建立一個多維陣列
data= np.array([
    [2, 1, 7],
    [3, -5, 8]
])

# 統計運算
data.sum()       #全部加總
data.sum(axis= 0)   #加總欄位 (Column)
data.sum(axis= 1)   #加總列  (Row)
data.min()       #全部最小值
data.cumsum()     #逐值累加
data.mean()      #平均數
data.std()       #母體標準差 (NumPy預設)
data.std(ddof=1)    #樣本標準差 (工程實驗常用)


--------(NumPy: 多維陣列 ndarray 基礎運算功能)--------

--------(Elementwise: 逐元運算)--------

data1: [ 3  2 10]
data2: [1 3 6]

【相加結果】: [ 4  5 16]
【乘法結果】: [ 3  6 60]
【data1 > data2】: [ True False  True]
【是否相等】: [False False False]

--------(Matrix: 矩陣運算)--------

data1: [[1 3]]
data2: 
[[ 2 -1  3]
 [-2  4  1]]

【內積結果】
[[-4 11  6]]

【張量外積結果】
[[ 2 -1  3 -2  4  1]
 [ 6 -3  9 -6 12  3]]

【向量外積 (叉積) 結果】: [0 0 1]

--------(Statistics: 統計運算)--------

data:
[[ 2  1  7]
 [-5  3  8]]

【總和】: 16
【最大值】: 8
【平均值】: 2.67
【母體標準差】: 4.27
【樣本標準差 (ddof=1)】4.68

【針對第一個維度 (axis=0) 做總和】: [-3  4 15]
【針對第二個維度 (axis=1) 做總和】: [10  6]
【針對第一個維度 (axis=0) 找最大值】: [2 3 8]
【針對第二個維度 (axis=1) 找平均值】: [3.33333333 2.        ]

【逐值累加】
[ 2  3 10  5  8 16]
【針對第一個維度做逐值累加】
[[ 2  1  7]
 [-3  4 15]]



np.float64(4.676180777800049)