<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_15_01%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E5%90%88%E4%BD%B5%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
print("--------(NumPy: 多維陣列 ndarray 合併操作)--------")

# 實際操作: 多維陣列的合併操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 準備測試資料
arr1 = np.array([  #2x3
    [1, 2, 3],
    [4, 5, 6]
])
arr2 = np.array([  #2x3
    [7, 8, 9],
    [10, 11, 12]
])
arr3 = np.array([  #2x2
    [13, 14],
    [15, 16]
])

# 合併第一個維度
result1 = np.vstack((arr1, arr2))
print(f"\n【arr1 陣列】\n{arr1}")
print(f"【arr2 陣列】\n{arr2}")
print(f"\n【合併 第一個維度 後的陣列】\n{result1}")
"""
  4x3
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
  ]
"""

# 合併第二個維度
result2 = np.hstack((arr1, arr2))
print(f"【合併 第二個維度 後的陣列】\n{result2}")
"""
  2x6
  [
    [1, 2, 3, 7, 8, 9],
    [4, 5, 6, 10, 11, 12]
  ]
"""

# 合併第二個維度 (三個陣列)
result3 = np.hstack((arr1, arr2, arr3))
print(f"【合併 第二個維度 (三個陣列) 後的陣列】\n{result3}")
"""
  2x8
  [
  [1, 2, 3, 7, 8, 9, 13, 14],
  [4, 5, 6, 10, 11, 12, 15, 16]
  ]
"""



#======================
# 合併 (Stacking)
#======================

# 合併操作
# 將數個多維陣列，合併成一個

# 合併第一個維度
# np.vstack((陣列一, 陣列二, ...))

# 合併第二個維度
# np.hstack((陣列一, 陣列二, ...))

#-------------------------------------------------------------

# 合併範例
arr1 = np.array([  #1x2
    [3, 4]
])
arr2 = np.array([  #1x2
    [5, 6]
])

result1 = np.vstack((arr1, arr2))
#[[3, 4],[5, 6]]  #2x2
result2 = np.hstack((arr1, arr2))
#[[3, 4, 5, 6]]  #1x4


--------(NumPy: 多維陣列 ndarray 合併操作)--------

【arr1 陣列】
[[1 2 3]
 [4 5 6]]
【arr2 陣列】
[[ 7  8  9]
 [10 11 12]]

【合併 第一個維度 後的陣列】
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
【合併 第二個維度 後的陣列】
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
【合併 第二個維度 (三個陣列) 後的陣列】
[[ 1  2  3  7  8  9 13 14]
 [ 4  5  6 10 11 12 15 16]]


In [92]:
import numpy as np
print("--------(NumPy: 多維陣列 ndarray 合併操作)--------")

#=================================================================
# 1. 垂直合併 (Vertical Stack): np.vstack()
# 像是疊積木一樣，把陣列「上下」疊起來，常用於「增加數據筆數」
#=================================================================
print("\n--------(垂直合併: np.vstack)--------")

# §實驗情境: 紀錄多個批次的感測器數據
# 假設分兩次量測了某個元件的電壓與電流 (2 欄 [V, I])
batch_1 = np.array([  #2x2
    [5.0, 0.2],
    [10.0, 0.4]
])
batch_2 = np.array([  #2x2
    [15.0, 0.6],
    [20.0, 0.8]
])

# 補充資訊: 合併的陣列需要使用「小括號」包成一個 Tuple ，例如 (arr1, arr2)
combined_v = np.vstack((batch_1, batch_2))
print(f"\n【第一批數據 batch_1】\n{batch_1}")         #2x2
print(f"【第二批數據 batch_2】\n{batch_2}")          #2x2
print(f"【垂直合併後的總數據】\n{combined_v}")
print(f"【垂直合併後的陣列形狀】: {combined_v.shape}\n")   #4x2


#=============================================================
# 2. 水平合併 (Horizontal Stack): np.hstack()
# 把陣列「左右」並排拼接，常用於「增加資料的欄位 (特徵)」
#=============================================================
print("--------(水平合併: np.hstack)--------")

# §實驗情境: 合併不同電路級 (Stages) 的節點電壓
# 假設這是一個多級放大器，分別將「第一級」與「第二級」電路的各三個節點電壓寫成 1x3 列向量
stage1_v = np.array([  #第一級節點電壓 [V1, V2, V3] (形狀: 1x3)
    [1.2, 2.5, 3.3]
])
stage2_v = np.array([  #第二級節點電壓 [V4, V5, V6] (形狀: 1x3)
    [4.1, 5.0, 4.8]
])

all_nodes_v = np.hstack((stage1_v, stage2_v))
print(f"\n【第一級節點電壓 stage1_v】\n{stage1_v}")
print(f"【第二級節點電壓 stage2_v】\n{stage2_v}")
print(f"【水平合併後的總節點電壓】\n{all_nodes_v}")
print(f"【水平合併後的陣列形狀】: {all_nodes_v.shape}\n") #形狀: 1x6


#=========================================================================
# 3. 實務進階應用: 製作實驗數據表 (將兩組一維數據合併成 3x2 表格)
#=========================================================================
print("--------(§實務進階應用: 製作實驗數據表)--------")


# §實驗情境: 將「時間」與「電壓」兩組一維數據，合併成二維資料表
time_1d = np.array([0.1, 0.2, 0.3])    #形狀:(3,) 一維陣列
voltage_1d = np.array([1.5, 3.2, 4.8])   #形狀:(3,) 一維陣列

# 語法陷阱回顧: 如果直接對一維陣列做 hstack，只會頭尾相接變成更長的一維陣列:[0.1, 0.2, 0.3, 1.5, 3.2, 4.8]
# 目前的需求: 左右並排的兩欄表格

# 解法: 可以利用最近學習到的 .reshape(-1, 1)，先把一維陣列轉換成「行向量 (Column Vector)」
t_col = time_1d.reshape(-1, 1)    #變成3x1
v_col = voltage_1d.reshape(-1, 1)   #變成3x1

# 現在兩個數據都是「直直的一行 (3x1)」了，就可以使用 .hstack 左右合併為 3x2 陣列
table = np.hstack((t_col, v_col))
print(f"\n【時間行向量 (3x1)】\n{t_col}")
print(f"【電壓行向量 (3x1)】\n{v_col}")
print(f"【水平合併後的表格 (Time, Voltage)】\n{table}")
print(f"【水平合併後的表格形狀】: {table.shape}\n")
#結果為 3x2 的實驗資料表

#-------------------------------------------------------------

# §補充技巧: np.column_stack() (直行堆疊)
# 這是 NumPy 專門用來處理上述情境的「作弊語法」
# 只要傳入一維陣列，會自動在底層把它們轉換成行向量並且左右合併，省去手動 reshape 的步驟
table_quick = np.column_stack((time_1d, voltage_1d))

print(f"【使用 column_stack 快速合併的表格】\n{table_quick}")
print(f"【快速合併後的表格形狀】: {table_quick.shape}\n")


#==========================================
# 4. 萬用合併函式: np.concatenate()
# 透過指定 axis (軸) 來決定合併方向
#==========================================
print("--------(萬用合併: np.concatenate)--------")

# 準備兩個 2x2 陣列
A = np.array([
    [1, 2],[3, 4]
])
B = np.array([
    [5, 6],[7, 8]
])

# axis= 0 代表針對第一個維度 (往下疊)，效果同等 vstack
concat_0 = np.concatenate((A, B), axis=0)
print(f"\n【concatenate (axis=0) 往下疊】\n{concat_0}")

# axis= 1 代表針對第二個維度 (往右接)，效果同等 hstack
concat_1 = np.concatenate((A, B), axis=1)
print(f"【concatenate (axis=1) 往右接】\n{concat_1}")


--------(NumPy: 多維陣列 ndarray 合併操作)--------

--------(垂直合併: np.vstack)--------

【第一批數據 batch_1】
[[ 5.   0.2]
 [10.   0.4]]
【第二批數據 batch_2】
[[15.   0.6]
 [20.   0.8]]
【垂直合併後的總數據】
[[ 5.   0.2]
 [10.   0.4]
 [15.   0.6]
 [20.   0.8]]
【垂直合併後的陣列形狀】: (4, 2)

--------(水平合併: np.hstack)--------

【第一級節點電壓 stage1_v】
[[1.2 2.5 3.3]]
【第二級節點電壓 stage2_v】
[[4.1 5.  4.8]]
【水平合併後的總節點電壓】
[[1.2 2.5 3.3 4.1 5.  4.8]]
【水平合併後的陣列形狀】: (1, 6)

--------(§實務進階應用: 製作實驗數據表)--------

【時間行向量 (3x1)】
[[0.1]
 [0.2]
 [0.3]]
【電壓行向量 (3x1)】
[[1.5]
 [3.2]
 [4.8]]
【水平合併後的表格 (Time, Voltage)】
[[0.1 1.5]
 [0.2 3.2]
 [0.3 4.8]]
【水平合併後的表格形狀】: (3, 2)

【使用 column_stack 快速合併的表格】
[[0.1 1.5]
 [0.2 3.2]
 [0.3 4.8]]
【快速合併後的表格形狀】: (3, 2)

--------(萬用合併: np.concatenate)--------

【concatenate (axis=0) 往下疊】
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
【concatenate (axis=1) 往右接】
[[1 2 5 6]
 [3 4 7 8]]
