<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_15%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E5%90%88%E4%BD%B5%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
print("--------(NumPy: 多維陣列 ndarray 合併操作)--------")

# 實際操作: 多維陣列的合併操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 準備測試資料
arr1 = np.array([  #2x3
    [1, 2, 3],
    [4, 5, 6]
])
arr2 = np.array([  #2x3
    [7, 8, 9],
    [10, 11, 12]
])
arr3 = np.array([  #2x2
    [13, 14],
    [15, 16]
])

# 合併第一個維度
result1 = np.vstack((arr1, arr2))
print(f"\n【arr1 陣列】\n{arr1}")
print(f"【arr2 陣列】\n{arr2}")
print(f"\n【合併 第一個維度 後的陣列】\n{result1}")
"""
  4x3
  [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
  ]
"""

# 合併第二個維度
result2 = np.hstack((arr1, arr2))
print(f"【合併 第二個維度 後的陣列】\n{result2}")
"""
  2x6
  [
    [1, 2, 3, 7, 8, 9],
    [4, 5, 6, 10, 11, 12]
  ]
"""

# 合併第二個維度 (三個陣列)
result3 = np.hstack((arr1, arr2, arr3))
print(f"【合併 第二個維度 (三個陣列) 後的陣列】\n{result3}")
"""
  2x8
  [
  [1, 2, 3, 7, 8, 9, 13, 14],
  [4, 5, 6, 10, 11, 12, 15, 16]
  ]
"""



#======================
# 合併 (Stacking)
#======================

# 合併操作
# 將數個多維陣列，合併成一個

# 合併第一個維度
# np.vstack((陣列一, 陣列二, ...))

# 合併第二個維度
# np.hstack((陣列一, 陣列二, ...))

#-------------------------------------------------------------

# 合併範例
arr1 = np.array([  #1x2
    [3, 4]
])
arr2 = np.array([  #1x2
    [5, 6]
])

result1 = np.vstack((arr1, arr2))
#[[3, 4],[5, 6]]  #2x2
result2 = np.hstack((arr1, arr2))
#[[3, 4, 5, 6]]   #1x4


--------(NumPy: 多維陣列 ndarray 合併操作)--------

【arr1 陣列】
[[1 2 3]
 [4 5 6]]
【arr2 陣列】
[[ 7  8  9]
 [10 11 12]]

【合併 第一個維度 後的陣列】
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
【合併 第二個維度 後的陣列】
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
【合併 第二個維度 (三個陣列) 後的陣列】
[[ 1  2  3  7  8  9 13 14]
 [ 4  5  6 10 11 12 15 16]]
