<a href="https://colab.research.google.com/github/u9828057/Python_Practice/blob/main/NumPy/Python_%E6%9A%91%E5%81%87%E7%B7%B4%E7%BF%92_08_14%3A%E3%80%90NumPy%E3%80%91%E5%A4%9A%E7%B6%AD%E9%99%A3%E5%88%97_ndarray_%E7%B4%A2%E5%BC%95%E3%80%81%E5%88%87%E7%89%87%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
print("--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------")

# 實際操作: 多維陣列的索引、切片操作

# 載入 NumPy
import numpy as np

#-------------------------------------------------------------

# 多維陣列的索引 Indexing
print("\n--------(索引: Indexing)--------")

# 單維度的資料
data = np.array([1, 5, 2, 10])
print(f"\n【原始資料 data】: {data}")
print(f"【取得 data[0] 的資料】: {data[0]}")
print(f"【取得 data[2] 的資料】: {data[2]}")

# 多維度的資料
data = np.array([
    [0, 1],[10, -5],[2, 6]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0,1] 的資料】: {data[0,1]}")   #1
print(f"【取得 data[1,0] 的資料】: {data[1,0]}")   #10
print(f"【取得 data[2,0] 的資料】: {data[2,0]}")   #2

#-------------------------------------------------------------

# 多維陣列的切片 Slicing
print("\n--------(切片: Slicing)--------")

# 單維度的切片
data = np.array([-1, -5, 2, 3])
print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0:3] 的資料】: {data[0:3]}")   #[-1, -5, 2]
print(f"【取得 data[:2] 的資料】: {data[:2]}")    #[-1, -5]
print(f"【取得 data[2:] 的資料】: {data[2:]}")    #[2, 3]
print(f"【取得 data[:] 的資料】: {data[:]}")     #[-1, -5, 2, 3]

# 多維度的切片
data = np.array([
    [0, 1, 2],[3, 4, 5],
    [5, 4, 3],[2, 1, 0]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[1:3, 0:2] 的資料】\n{data[1:3, 0:2]}")   #[[3, 4],[5, 4]]
print(f"【取得 data[0:2, 1] 的資料】\n{data[0:2, 1]}")     #[1, 4]


# §補充資料:
# 使用單一數字（整數）來取值時，NumPy 會進行「降維」；而使用範圍切片（:）時，則會「保留原有的維度」
# 範例: print(f"【取得 data[0:2, 1:2] 的資料】\n{data[0:2, 1:2]}")
# 輸出: [[1],[4]]


# 使用 ... 代表「我全都要」
data = np.array([
    [
        [8, 1, 3],
        [-5, 5, 2]
    ],
    [
        [0, 1, 6],
        [4, 4, -3]
    ]
])

print(f"\n【原始資料 data】\n{data}")
print(f"【取得 data[0, ...] 的資料】\n{data[0, ...]}")
# 輸出: [[8, 1, 3],[-5, 5, 2]]

print(f"【取得 data[..., 1:3] 的資料】\n{data[..., 1:3]}")
# 輸出: [[[1, 3],[5, 2]],[[1, 6],[4, -3]]]













#======================
# 索引 (Indexing)
#======================

# 資料的索引

# 概念上和 Python 列表的索引相同
# 按照順序，每個資料都有一個索引 (編碼)，從 0 開始遞增
# 透過 多維陣列[索引] 的語法可以取得對應的資料

data = np.array([3, 4, 1])

data[0]  #3
data[1]  #4
data[2]  #1

#-------------------------------------------------------------

# 多維度資料的索引

# 使用逗號分開不同維度的索引
# 透過 多維陣列[索引,索引,...] 的語法可以取得對應的資料

data = np.array([
    [1, 5, 2],
    [3, -1, 10]
])

data[0,2]  #2
data[1,1]  #-1
data[1,0]  #3


#=====================
# 切片 (Slicing)
#=====================

# 資料的切片

# 取得多維陣列中的部分資料
# 以下語法取得對應的資料 多維陣列[開始索引 : 結束索引]

data = np.array([3, 4, 1, 5])
data[0:2]  #[3, 4]
data[1:4]  #[4, 1, 5]
data[2:]  #[1, 5]
data[:3]  #[3, 4, 1]
data[:]  #[3, 4, 1, 5]

#-------------------------------------------------------------

# 多維度資料的切片

# 分別決定每一個維度的索引範圍
# 以下語法取得對應的資料
# 多維陣列[
#    開始索引:結束索引,
#    開始索引:結束索引
#    ...
#    ]

data = np.array([
    [3, 1, 2],[1, 2, 5],
    [5, 2, 2],[3, -5, 1]
])

data[2:4, 1:3]  #[[2, 2],[-5, 1]]
data[0:2, 1]   #[1, 2]

#-------------------------------------------------------------

# 多維度資料的切片

# 使用 ... 代表「我全都要」
# 參考以下範例

data = np.array([
    [
        [3, 1, 2],[1, 0, 5]
    ],
    [
        [5, 4, 3],[1, 3, -3]
    ]
])

data[1,...]  #[[5, 4, 3],[1, 3, -3]]
data[...,0:2] #[[[3, 1],[1, 0]],[[5, 4],[1, 3]]]


--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------

--------(索引: Indexing)--------

【原始資料 data】: [ 1  5  2 10]
【取得 data[0] 的資料】: 1
【取得 data[2] 的資料】: 2

【原始資料 data】
[[ 0  1]
 [10 -5]
 [ 2  6]]
【取得 data[0,1] 的資料】: 1
【取得 data[1,0] 的資料】: 10
【取得 data[2,0] 的資料】: 2

--------(切片: Slicing)--------

【原始資料 data】
[-1 -5  2  3]
【取得 data[0:3] 的資料】: [-1 -5  2]
【取得 data[:2] 的資料】: [-1 -5]
【取得 data[2:] 的資料】: [2 3]
【取得 data[:] 的資料】: [-1 -5  2  3]

【原始資料 data】
[[0 1 2]
 [3 4 5]
 [5 4 3]
 [2 1 0]]
【取得 data[1:3, 0:2] 的資料】
[[3 4]
 [5 4]]
【取得 data[0:2, 1] 的資料】
[1 4]

【原始資料 data】
[[[ 8  1  3]
  [-5  5  2]]

 [[ 0  1  6]
  [ 4  4 -3]]]
【取得 data[0, ...] 的資料】
[[ 8  1  3]
 [-5  5  2]]
【取得 data[..., 1:3] 的資料】
[[[ 1  3]
  [ 5  2]]

 [[ 1  6]
  [ 4 -3]]]


array([[[3, 1],
        [1, 0]],

       [[5, 4],
        [1, 3]]])

In [97]:
import numpy as np
print("--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------")

#==========================================================
# 1. 一維陣列的索引與切片 (1D Indexing / Slicing)
# 語法邏輯: array[start : stop : step] (包含 start，不包含 stop)
#==========================================================
print("\n--------(一維陣列: 基礎切片)--------")

# 假設這是一秒鐘內，每 0.1 秒記錄一次的感測器數據 (長度 10)
data_1d = np.arange(10, 20)
#[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
#索引: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

# 取得特定範圍 (取得索引 2 到 4 的資料)
print(f"\n【取索引 2～4】: {data_1d[2:5]}")

# 加上步長 (Step): 每隔兩步取一個值
print(f"【每隔兩步取樣一次】: {data_1d[::2]}")

# 實用技巧: 陣列反轉 (在數位訊號處理的時間反轉很常使用)
print(f"【陣列資料反轉】: {data_1d[::-1]}")


#=========================================================================
# 2. 多維陣列的索引與切片 (Multi-dimensional Indexing & Slicing)
# 語法邏輯: array[ 列的切片, 欄的切片 ]
# 這是 NumPy 強大的功能，需要習慣使用逗號 「,」來分隔維度
#=========================================================================
print("\n--------(多維陣列: 矩陣切片)--------")

# 假設這是一個 3x3 的工程數學轉換矩陣
matrix_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"\n【原始 3x3 矩陣】\n{matrix_3x3}")


# A. 精準定位單一元素
# 取得第一列、第二欄的元素
print(f"【取得矩陣索引 [1, 2] 的資料】: {matrix_3x3[1, 2]}")  #6

# B. 取得整列 (Row) 或整欄 (Column)
# 冒號 (:) 代表這個維度我全都要
print(f"【取得第 0 列的所有資料】: {matrix_3x3[0, :]}")  #[1, 2, 3]
print(f"【取得第 1 欄的所有資料】: {matrix_3x3[:, 1]}")  #[2, 5, 8]

# §補充資料:
# 使用單一數字（整數）來取值時，NumPy 會進行「降維」；而使用範圍切片（:）時，則會「保留原有的維度」
# 範例: print(f"【取得 data[0:2, 1:2] 的資料】\n{data[0:2, 1:2]}")
# 輸出: [[1],[4]]

# C. 擷取子矩陣 (Sub-matrix)
# 取得左上角的 2x2 子矩陣 (取列 0～1，欄 0～1)
sub_matrix = matrix_3x3[0:2, 0:2]
print(f"【取得左上角 2x2 子矩陣】\n{sub_matrix}\n")


#=====================================================================
# 3. 布林遮罩 (Boolean Masking) - 條件篩選
# 自動過濾出符合條件的數據，完全不需要寫 for 迴圈與 if 判斷式
#=====================================================================
print("--------(進階技巧: 布林遮罩 Boolean Mask)--------")

# §實驗情境: 異常電壓突波 (Surge) 篩選
# 假設這是示波器量測到的電壓值，安全上限為 5.0V
voltage_data = np.array([1.2, 5.8, 2.0, 1.8, 6.1, 1.9, 5.2])
print(f"\n【原始電壓數據】: {voltage_data}")


# 步驟 1: 建立布林條件 (找出大於 5.0 的值)
# 程式會逐元比較，回傳一個全都是 True/False 的陣列
mask = voltage_data > 5.0
print(f"【布林遮罩陣列】: {mask}")

# 步驟 2: 將遮罩「套用」回原陣列 (像篩網一樣把 True 留下)
danger_voltage = voltage_data[mask]
print(f"【篩選出的異常電壓】: {danger_voltage}")

# 實務上通常會把步驟 1、2 寫在一起，簡化成一行
print(f"【一行搞定篩選】: {voltage_data[voltage_data > 5.0]}")

# 延伸應用: 將異常值強制修正 (例如將超過 5.0V 的數據全部削波限制在 5.0V)
voltage_data[voltage_data > 5.0] = 5.0
print(f"【削波限制後的安全電壓】: {voltage_data}")

#-------------------------------------------------------------

# §補充技巧 A: 多重條件篩選 (&: 且 ,|: 或)

# 需求: 找出介於 2.0V (含) 到 5.0V (含) 之間的正常工作電壓
# 每個條件都必須用小括號 () 刮起來
normal_mask = (voltage_data >= 2.0) & (voltage_data <= 5.0)
print(f"【正常電壓篩選】: {voltage_data[normal_mask]}")

#備註: 此處的 voltage_data 在上一步已經被削波限制過，所以大於 5.0 的值都已變成 5.0


# §補充技巧 B: np.where(條件, 成立時給的值, 不成立時給的值)

# 需求: 把大於 5.0V 的變成 5.0V (削波)，小於 0V 的變成 0V (整流)，其餘保持原樣
raw_signal = np.array([-1.5, 3.2, 6.5, 4.0, -0.8])

# 限制上限 5.0V (大於 5.0 就變 5.0，否則維持原樣)
clipped_signal = np.where(raw_signal > 5.0, 5.0, raw_signal)
# 接著限制下限 0V (小於 0 就變 0，否則維持原樣)
final_signal = np.where(clipped_signal < 0.0, 0.0, clipped_signal)

print(f"【原始訊號】: {raw_signal}")
print(f"【經過雙向限制後的訊號】: {final_signal}")


--------(NumPy: 多維陣列 ndarray 索引、切片操作)--------

--------(一維陣列: 基礎切片)--------

【取索引 2～4】: [12 13 14]
【每隔兩步取樣一次】: [10 12 14 16 18]
【陣列資料反轉】: [19 18 17 16 15 14 13 12 11 10]

--------(多維陣列: 矩陣切片)--------

【原始 3x3 矩陣】
[[1 2 3]
 [4 5 6]
 [7 8 9]]
【取得矩陣索引 [1, 2] 的資料】: 6
【取得第 0 列的所有資料】: [1 2 3]
【取得第 1 欄的所有資料】: [2 5 8]
【取得左上角 2x2 子矩陣】
[[1 2]
 [4 5]]

--------(進階技巧: 布林遮罩 Boolean Mask)--------

【原始電壓數據】: [1.2 5.8 2.  1.8 6.1 1.9 5.2]
【布林遮罩陣列】: [False  True False False  True False  True]
【篩選出的異常電壓】: [5.8 6.1 5.2]
【一行搞定篩選】: [5.8 6.1 5.2]
【削波限制後的安全電壓】: [1.2 5.  2.  1.8 5.  1.9 5. ]
【正常電壓篩選】: [5. 2. 5. 5.]
【原始訊號】: [-1.5  3.2  6.5  4.  -0.8]
【經過雙向限制後的訊號】: [0.  3.2 5.  4.  0. ]
